#!/usr/bin/perl

package SSP;

use strict;
use warnings;
use diagnostics;

$ENV{'PATH'} = '/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin';

use lib '../lib';
use Term::ANSIColor qw( :constants );
use Vars;
use PreFlightChecks;
use Cmd;
use PrintText;
use Tips;

use Info::HostName;

use Warn::OS;
use Warn::Cron;
use Warn::Upcp;
use Warn::Loopback;
use Warn::Cpanel;
use Warn::EasyApache;
use Warn::Apache;
use Warn::Tomcat;
use Warn::Permissions;
use Warn::DiskUsage;
use Warn::PureFTPd;
use Warn::Hooks;
use Warn::PostgreSQL;
use Warn::Exim;
use Warn::DisabledServices;
use Warn::Horde;
use Warn::Roundcube;
use Warn::ModSec;
use Warn::PHP;
use Warn::Perl;
use Warn::MySQL;
use Warn::DNS;
use Warn::Yum;
use Warn::ImageMagick;
use Warn::RPM;

use ThirdParty::ASSP;
use ThirdParty::Varnish;
use ThirdParty::LiteSpeed;
use ThirdParty::Nginx;
use ThirdParty::MailScanner;
use ThirdParty::APF;
use ThirdParty::CSF;
use ThirdParty::PRM;
use ThirdParty::LES;
use ThirdParty::Webmin;
use ThirdParty::Symantec;
use ThirdParty::HAProxy;
use ThirdParty::OneH;

{
    local @INC = ( @INC, "/usr/local/cpanel" );
    eval { local $SIG{__DIE__}; local $SIG{__WARN__}; require Cpanel::CachedCommand; };
}

PreFlightChecks::check_for_freebsd();
PreFlightChecks::check_if_root();
PreFlightChecks::check_for_cpanel();
PreFlightChecks::print_nopaste();
Tips::print_tip();
PreFlightChecks::print_ssp_version();

## [INFO]
Info::HostName::print_hostname( $hostname );

## [WARN]
Warn::OS::check_selinux_status();
Warn::OS::check_runlevel();
Warn::Cron::check_for_missing_root_cron();
Warn::Cron::check_roots_cron_for_certain_commands();
Warn::Cron::check_cron_process();
Warn::Cron::check_for_harmful_php_mode_600_cron();
Warn::Upcp::check_if_upcp_is_running();
Warn::Upcp::check_for_stale_upgrade_in_progress_txt();
Warn::Cpanel::check_cpanelconfig_filetype();
Warn::Cpanel::check_cpanelsync_exclude();
Warn::EasyApache::check_for_rawopts();
Warn::EasyApache::check_for_rawenv();
Warn::EasyApache::check_for_custom_opt_mods();
Warn::EasyApache::check_for_local_makecpphp_template( $cpanel_version );
Warn::EasyApache::check_easy_skip_cpanelsync();
Warn::EasyApache::check_for_apache_update_no_restart();
Warn::EasyApache::check_for_stale_easyapache_build_file();
Warn::EasyApache::check_if_easyapache_is_running();
Warn::EasyApache::check_for_easyapache_hooks();
Warn::EasyApache::check_for_empty_easyapache_profiles();
Warn::Apache::check_for_local_apache_templates();
Warn::Apache::check_for_custom_apache_includes();
Warn::Apache::check_for_huge_apache_logs();
Warn::Apache::check_for_empty_apache_templates();
Warn::Apache::check_for_missing_or_commented_customlog( @apache_version_output );
Warn::Apache::check_if_httpdconf_ipaddrs_exist( @local_ipaddrs_list );
Warn::Apache::check_distcache_and_libapr();
Warn::Apache::check_for_apache_rlimits();
Warn::Apache::check_for_apache_listen_host_is_localhost();
Warn::Apache::check_for_var_cpanel_conf_apache_local();
Warn::Apache::check_for_maxclients_or_maxrequestworkers_reached( @apache_version_output );
Warn::Apache::check_for_bw_module_and_more_than_1024_vhosts( @apache_modules_output );
Warn::Apache::check_for_sneaky_htaccess();
Warn::Tomcat::check_for_tomcatoptions();
Warn::Permissions::check_for_non_default_permissions( $cpanel_version_major, $cpanel_version_minor );
Warn::Permissions::check_awstats_permissions();
Warn::DiskUsage::check_disk_space();
Warn::DiskUsage::check_disk_inodes();
Warn::Cpanel::check_var_cpanel_users_files_ownership();
Warn::Cpanel::check_root_suspended();
Warn::Cpanel::check_for_domain_forwarding();
Warn::Cpanel::check_usr_local_cpanel_path_for_symlinks();
Warn::Cpanel::check_for_cpanel_files();
Warn::Cpanel::check_wwwacctconf_for_incorrect_minuid();
Warn::Cpanel::check_for_cpsources_conf();
Warn::Cpanel::check_for_extra_uid0_pwcache_file( $cpanel_version_major, $cpanel_version_minor );
Warn::Cpanel::check_for_11_30_scripts_not_a_symlink( $cpanel_version );
Warn::Cpanel::check_var_cpanel_immutable_files();
Warn::Cpanel::check_for_cpanel_CN_newline();
Warn::Cpanel::check_cpanel_config_for_low_maxmem( %cpconf );
Warn::Cpanel::check_for_empty_or_missing_files();
Warn::Cpanel::check_for_C_compiler_optimization();
Warn::Cpanel::check_for_fork_bomb_protection();
Warn::Cpanel::check_for_cPanel_lower_than_11_30_7_3( $cpanel_version );
Warn::Cpanel::check_for_mainip_newline();
Warn::Cpanel::check_for_skiphttpauth_disabled();
Warn::Cpanel::check_for_use_compiled_dnsadmin();
Warn::Cpanel::check_for_jailshell_additional_mounts_trailing_slash();
Warn::Cpanel::check_for_invalid_HOMEDIR();
Warn::Cpanel::check_pkgacct_override();
Warn::Cpanel::check_for_custom_locales();
Warn::Cpanel::check_for_rpmsave_conf();
Warn::PureFTPd::check_pure_ftpd_conf_for_upload_script_and_dead( \%cpconf, \%pureftpdconf );
Warn::Hooks::check_for_custom_event_handler();
Warn::Hooks::check_for_hooks_in_scripts_directory();
Warn::Hooks::check_for_usr_local_cpanel_hooks();
Warn::Hooks::check_for_hooks_from_var_cpanel_hooks_yaml();
Warn::PostgreSQL::check_for_empty_postgres_config();
Warn::PostgreSQL::check_for_custom_postgres_repo();
Warn::Exim::check_for_custom_exim_conf_local();
Warn::Exim::check_eximstats_size( $mysql_datadir );
Warn::Exim::check_eximstats_corrupt( $mysql_error_log );
Warn::OS::check_for_gdm();
Warn::OS::check_limitsconf();
Warn::OS::check_for_redhat_firewall();
Warn::OS::check_for_home_noexec();
Warn::OS::check_for_oracle_linux();
Warn::OS::check_for_proc_mdstat_recovery();
Warn::OS::check_for_system_mem_below_512M();
Warn::OS::check_for_usr_local_lib_libz_so();
Warn::OS::check_etc_hosts_sanity( $hostname );
Warn::OS::check_for_kernel_headers_rpm();
Warn::OS::check_for_low_ulimit_for_root();
Warn::OS::check_for_clock_skew();
Warn::OS::check_for_zlib_h();
Warn::OS::check_for_noxsave_in_grub_conf();
Warn::OS::check_for_networkmanager();
Warn::OS::check_for_dhclient();
Warn::OS::check_for_missing_etc_localtime();
Warn::OS::check_for_immutable_files();
Warn::OS::check_for_uppercase_chars_in_hostname( $hostname );
Warn::OS::check_for_usr_local_include_jpeglib_h();
Warn::OS::check_for_non_default_umask();
Warn::OS::check_for_extra_uid_0_user();   # this is NOT a security check, but for FB 62467
Warn::OS::check_bash_history_for_certain_commands();
Warn::DisabledServices::check_for_disabled_services();
Warn::Horde::check_for_hordepass_newline();
Warn::Roundcube::check_for_var_cpanel_roundcube_install();
Warn::Roundcube::check_roundcube_mysql_pass_mismatch();
Warn::ModSec::check_for_non_default_modsec_rules( @apache_modules_output );
Warn::PHP::check_for_sql_safe_mode();
Warn::PHP::check_for_missing_timezone_from_phpini();
Warn::PHP::check_pecl_phpini_location();
Warn::PHP::check_for_homeloader_php_extension();
Warn::PHP::check_for_phphandler_and_opcode_caching_incompatibility();
Warn::Perl::check_for_PERL5LIB_env_var();
Warn::Perl::check_for_broken_list_util();
Warn::Perl::check_perl_version_less_than_5_8();
Warn::Perl::check_perl_sanity();
Warn::Perl::check_for_missing_perl_modules();
Warn::Loopback::check_if_loopback_is_up();
Warn::Loopback::check_loopback_connectivity();
Warn::MySQL::check_mysql_non_default_datadir();
Warn::MySQL::check_mysqld_warnings_errors();
Warn::MySQL::check_for_non_default_mysql_error_log_location();
Warn::MySQL::check_for_my_cnf_skip_name_resolve();
Warn::MySQL::check_for_my_cnf_sql_mode();
Warn::MySQL::check_for_mysql_root_pass_with_single_quote();
Warn::DNS::check_for_options_rotate_redhat_centos_63();
Warn::DNS::check_for_allow_query_localhost();
Warn::DNS::check_for_bad_permissions_on_named_ca();
Warn::Yum::check_for_missing_yumconf();
Warn::Yum::check_for_empty_yumconf();
Warn::Yum::check_for_wget_exclude();
Warn::Yum::check_for_odd_yumconf();
Warn::ImageMagick::check_for_multiple_imagemagick_installs();
Warn::RPM::check_for_rpm_overrides();
Warn::OS::check_for_direct_nfs_backup();

## [3RDP]
ThirdParty::ASSP::assp();
ThirdParty::Varnish::varnish();
ThirdParty::LiteSpeed::litespeed();
ThirdParty::Nginx::nginx();
ThirdParty::MailScanner::mailscanner();
ThirdParty::APF::apf();
ThirdParty::CSF::csf();
ThirdParty::PRM::prm();
ThirdParty::LES::les();
ThirdParty::Webmin::webmin();
ThirdParty::Symantec::symantec();
ThirdParty::HAProxy::haproxy();
ThirdParty::OneH::one_h();

1;
